### ISSUE TITLE
cannot build

### ISSUE THREAD

**Issue by alex-georgiou** [nym-zone/segvan#4]
Hello,

I'm trying to build `segvan` but I'm failing. Probably because I don't know much about C or its libraries. This is what I've done so far:

`sudo apt install libbitcoin-dev`

`cmake .`

Then, when I do a make:

    $ make
    [ 50%] Building CXX object CMakeFiles/segvan.dir/segvan.cpp.o
    /home/alexg/coins/segvan/segvan.cpp:23:29: error: ‘chain’ is not a namespace-name
     using namespace libbitcoin::chain;
                                 ^~~~~
    /home/alexg/coins/segvan/segvan.cpp:23:34: error: expected namespace-name before ‘;’ token
     using namespace libbitcoin::chain;
                                      ^

There are more errors that I did not include here. My guess is that I have the wrong version of libbitcoin? This is the version I have:

    $ apt show libbitcoin-dev
    Package: libbitcoin-dev
    Version: 2.11.0-1ubuntu2

I would appreciate it if anyone could give me some pointers as to how to build the tool in Linux, either in Ubuntu or in any other distro if needed.

Thank you.

**Comment by matthewincognito** [comment]
>[ 50%] Building CXX object CMakeFiles/segvan.dir/segvan.cpp.o

Where did you download segvan from? That looks like CMake and C++ (the segvan in this repository uses neither of these).

**Comment by alex-georgiou** [comment]
OMG you're right, I'm stupid. I had a totally different segvan.

I cloned this repo and ran `make`, it seems it now can't link to `libgmp`:

	cc -O2 -std=c11   -c -o segwit_addr.o segwit_addr.c
	cc -L./secp256k1/.libs -o segvan segvan.o segwit_addr.o -lsecp256k1 -lcrypto
	./secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_mod_inverse':
	/home/alexg/coins/segvan/secp256k1/src/num_gmp_impl.h:128: undefined reference to `__gmpn_gcdext'
	./secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `__gmpn_sub':
	/usr/include/x86_64-linux-gnu/gmp.h:2190: undefined reference to `__gmpn_sub_n'
	./secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_set_bin':
	/home/alexg/coins/segvan/secp256k1/src/num_gmp_impl.h:49: undefined reference to `__gmpn_set_str'
	/home/alexg/coins/segvan/secp256k1/src/num_gmp_impl.h:49: undefined reference to `__gmpn_set_str'
	./secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_get_bin':
	/home/alexg/coins/segvan/secp256k1/src/num_gmp_impl.h:34: undefined reference to `__gmpn_get_str'
	./secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_set_bin':
	/home/alexg/coins/segvan/secp256k1/src/num_gmp_impl.h:49: undefined reference to `__gmpn_set_str'
	/home/alexg/coins/segvan/secp256k1/src/num_gmp_impl.h:49: undefined reference to `__gmpn_set_str'
	./secp256k1/.libs/libsecp256k1.a(libsecp256k1_la-secp256k1.o): In function `secp256k1_num_get_bin':
	/home/alexg/coins/segvan/secp256k1/src/num_gmp_impl.h:34: undefined reference to `__gmpn_get_str'
	collect2: error: ld returned 1 exit status
	GNUmakefile:18: recipe for target 'segvan' failed
	make: *** [segvan] Error 1

I'm not sure how Makefiles work but I was able to compile the binary, by repeating the last `cc` command with `-lgmp` added, i.e.:

	cc -L./secp256k1/.libs -o segvan segvan.o segwit_addr.o -lsecp256k1 -lcrypto -lgmp

I was able to run it thanks to the instructions that you have posted here: https://bitcointalk.org/index.php?topic=2934774.msg31615993#msg31615993

Thank you!
:-)

**Comment by matthewincognito** [comment]
No problem, I'm glad you've got it working now.

>I'm not sure how Makefiles work but I was able to compile the binary,
>by repeating the last cc command with -lgmp added, i.e.:

I'm not sure why you had to add that, it should've been added
automatically because libsecp256k1 depends on libgmp. @nym-zone - any ideas?
