### ISSUE TITLE
ripped.h file missing, cannot "make"

### ISSUE THREAD

**Issue by HeroHann** [nym-zone/segvan#6]
segvan.c:76:10: fatal error: 'openssl/ripemd.h' file not found
#include <openssl/ripemd.h>

What to do now?

**Comment by katesalazar** [comment]
I'd try getting libssl-dev, what's the OS?

**Comment by katesalazar** [comment]
to be clear, I was able to build out of the box

**Comment by katesalazar** [comment]
and it's apparently throwing successes for syntax like:

./segvan -r ^bc1qstuff

watch your spelling cuz if you enter a character
not in the base32 catalogue, it won't tell you so

**Comment by HeroHann** [comment]
I long moved on...dint care anymore😅
